#!/bin/bash

configfile=/home/mhassel/vms/vm00/conf/vfio-pci00.conf

vfiobind() {
    dev="$1"
        vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
        device=$(cat /sys/bus/pci/devices/$dev/device)
        if [ -e /sys/bus/pci/devices/$dev/driver ]; then
                echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
        fi
        echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id

}

modprobe vfio-pci

cat $configfile | while read line;do
    echo $line | grep ^# >/dev/null 2>&1 && continue
        vfiobind $line
done

sudo qemu-system-x86_64 -enable-kvm -M q35 -m 4096 -cpu host \
-smp 4,sockets=1,cores=4,threads=1 \
-device vfio-pci,host=2:00.0,multifunction=on,x-vga=on \
-device vfio-pci,host=2:00.1,bus=pcie.0 \
-drive if=pflash,format=raw,readonly,file=/home/mhassel/vms/vm00/OVMF/OVMF_CODE.fd \
-drive if=pflash,format=raw,file=/home/mhassel/vms/vm00/OVMF/OVMF_VARS.fd \
-device virtio-scsi-pci,id=scsi \
-drive file=/home/mhassel/Downloads/iso/win.iso,id=isocd,format=raw,if=none -device scsi-cd,drive=isocd
#-bios /usr/share/seabios/bios.bin -vga none \
#-bios /home/mhassel/vms/vm00/OVMF/OVMF_CODE.fd -vga none \
#-drive if=none,file=/home/mhassel/vms/vm00/disk/windows00.img,id=disk,format=raw -device ide-hd,bus=piix4-ide.0,drive=disk \
#-boot menu=on

exit 0
