#!/bin/bash

configfile=/wrk/vms/vm00/conf/vfio-pci00.conf

vfiobind() {
    dev="$1"
        vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
        device=$(cat /sys/bus/pci/devices/$dev/device)
        if [ -e /sys/bus/pci/devices/$dev/driver ]; then
                echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
        fi
        echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id

}

modprobe vfio-pci

cat $configfile | while read line;do
    echo $line | grep ^# >/dev/null 2>&1 && continue
        vfiobind $line
done

sudo qemu-system-x86_64 -enable-kvm -M q35 -m 4096 -cpu host \
-smp 4,sockets=1,cores=4,threads=1 \
-device vfio-pci,host=2:00.0,multifunction=on,x-vga=on,rombar=0 \
-device vfio-pci,host=2:00.1,bus=pcie.0 \
-device vfio-pci,host=3:00.0,bus=pcie.0 \
-drive if=pflash,format=raw,readonly,file=/wrk/vms/vm00/ovmf/OVMF_CODE.fd \
-drive if=pflash,format=raw,file=/wrk/vms/vm00/ovmf/OVMF_VARS.fd \
-drive file=/wrk/vms/vm00/disk/vm00-win00.internal.matthassel.com,index=0,media=disk,format=raw,if=virtio \
-drive file=/wrk/vms/vm00/iso/Win10_1703_English_x64.iso,index=2,media=cdrom \
-drive file=/wrk/vms/vm00/iso/virtio-win-0.1.126.iso,index=3,media=cdrom \
-boot menu=on
#-device virtio-scsi-pci,id=scsi \
#-device scsi-hd,drive=disk \
#-drive if=none,file=/home/mhassel/Downloads/iso/win10.iso,id=isocd,format=raw \
#-device scsi-cd,drive=isocd \
#-drive if=none,file=/home/mhassel/vms/vm00/disk/vm00.img,id=disk,format=raw \

exit 0
