#!/bin/bash

#configfile=/wrk/vms/win00/conf/vfio-pci.conf
#
#vfiobind() {
#    dev="$1"
#        vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
#        device=$(cat /sys/bus/pci/devices/$dev/device)
#        if [ -e /sys/bus/pci/devices/$dev/driver ]; then
#                echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
#        fi
#        echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id
#
#}
#
#modprobe vfio-pci
#
#cat $configfile | while read line;do
#    echo $line | grep ^# >/dev/null 2>&1 && continue
#        vfiobind $line
#done

sudo qemu-system-x86_64 -enable-kvm -M q35 -m 8192 -cpu host \
-vga std \
-alt-grab \
-no-quit \
-smp 4,sockets=1,cores=4,threads=1 \
-drive if=pflash,format=raw,readonly,file=/wrk/vms/win00/ovmf/OVMF_CODE.fd \
-drive if=pflash,format=raw,file=/wrk/vms/win00/ovmf/OVMF_VARS.fd \
-drive file=/wrk/vms/win00/disk/vm00-win00.internal.matthassel.com,index=0,media=disk,format=raw,if=virtio \
-drive file=/wrk/vms/win00/iso/Win10_1703_English_x64.iso,index=2,media=cdrom \
-drive file=/wrk/vms/win00/iso/virtio-win-0.1.126.iso,index=3,media=cdrom \
-boot menu=on

exit 0
